
"use client"
import "../../assets/style/globals.scss"
import ContextProvider from "../../context/ContextProvider"
import Script from 'next/script';



/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({ children }) {
  return (
    <ContextProvider>
       <html lang="fr">
      
      <body>
        {children}
      </body>
    </html>
    </ContextProvider>
   
  );
}
