export const countryCodes = {
    'Afghanistan': 'AF',
    'Albanie': 'AL',
    'Algérie': 'DZ',
    'Andorre': 'AD',
    'Angola': 'AO',
    'Antigua-et-Barbuda': 'AG',
    'Argentine': 'AR',
    'Arménie': 'AM',
    'Australie': 'AU',
    'Autriche': 'AT',
    'Azerbaïdjan': 'AZ',
    'Bahamas': 'BS',
    'Bahreïn': 'BH',
    'Bangladesh': 'BD',
    'Barbade': 'BB',
    'Biélorussie': 'BY',
    'Belgique': 'BE',
    'Belize': 'BZ',
    'Bénin': 'BJ',
    'Bhoutan': 'BT',
    'Bolivie': 'BO',
    'Bosnie-Herzégovine': 'BA',
    'Botswana': 'BW',
    'Brésil': 'BR',
    'Brunei': 'BN',
    'Bulgarie': 'BG',
    'Burkina Faso': 'BF',
    'Burundi': 'BI',
    'Cap-Vert': 'CV',
    'Cambodge': 'KH',
    'Cameroun': 'CM',
    'Canada': 'CA',
    'République centrafricaine': 'CF',
    'Tchad': 'TD',
    'Chili': 'CL',
    'Chine': 'CN',
    'Colombie': 'CO',
    'Comores': 'KM',
    'Congo': 'CG',
    'République du Congo (République Démocratique)': 'CD',
    'Costa Rica': 'CR',
    'Croatie': 'HR',
    'Cuba': 'CU',
    'Chypre': 'CY',
    'République tchèque': 'CZ',
    'Danemark': 'DK',
    'Djibouti': 'DJ',
    'Dominique': 'DM',
    'République Dominicaine': 'DO',
    'Équateur': 'EC',
    'Égypte': 'EG',
    'Salvador': 'SV',
    'Guinée équatoriale': 'GQ',
    'Érythrée': 'ER',
    'Estonie': 'EE',
    'Eswatini': 'SZ',
    'Éthiopie': 'ET',
    'Fidji': 'FJ',
    'Finlande': 'FI',
    'France': 'FR',
    'Gabon': 'GA',
    'Gambie': 'GM',
    'Géorgie': 'GE',
    'Allemagne': 'DE',
    'Ghana': 'GH',
    'Grèce': 'GR',
    'Grenade': 'GD',
    'Guatemala': 'GT',
    'Guinée': 'GN',
    'Guinée-Bissau': 'GW',
    'Guyane': 'GY',
    'Haïti': 'HT',
    'Honduras': 'HN',
    'Hongrie': 'HU',
    'Islande': 'IS',
    'Inde': 'IN',
    'Indonésie': 'ID',
    'Iran': 'IR',
    'Irak': 'IQ',
    'Irlande': 'IE',
    'Italie': 'IT',
    'Jamaïque': 'JM',
    'Japon': 'JP',
    'Jordanie': 'JO',
    'Kazakhstan': 'KZ',
    'Kenya': 'KE',
    'Kiribati': 'KI',
    'Corée du Nord': 'KP',
    'Corée du Sud': 'KR',
    'Koweït': 'KW',
    'Kirghizistan': 'KG',
    'Laos': 'LA',
    'Lettonie': 'LV',
    'Liban': 'LB',
    'Lesotho': 'LS',
    'Liberia': 'LR',
    'Libye': 'LY',
    'Liechtenstein': 'LI',
    'Lituanie': 'LT',
    'Luxembourg': 'LU',
    'Madagascar': 'MG',
    'Malawi': 'MW',
    'Malaisie': 'MY',
    'Maldives': 'MV',
    'Mali': 'ML',
    'Malte': 'MT',
    'Îles Marshall': 'MH',
    'Mauritanie': 'MR',
    'Maurice': 'MU',
    'Mexique': 'MX',
    'Micronésie': 'FM',
    'Moldavie': 'MD',
    'Monaco': 'MC',
    'Mongolie': 'MN',
    'Monténégro': 'ME',
    'Maroc': 'MA',
    'Mozambique': 'MZ',
    'Myanmar': 'MM',
    'Namibie': 'NA',
    'Nauru': 'NR',
    'Népal': 'NP',
    'Pays-Bas': 'NL',
    'Nouvelle-Zélande': 'NZ',
    'Nicaragua': 'NI',
    'Niger': 'NE',
    'Nigeria': 'NG',
    'Macédoine du Nord': 'MK',
    'Norvège': 'NO',
    'Oman': 'OM',
    'Pakistan': 'PK',
    'Palaos': 'PW',
    'Palestine':'PS',
    'Panama': 'PA',
    'Papouasie-Nouvelle-Guinée': 'PG',
    'Paraguay': 'PY',
    'Pérou': 'PE',
    'Philippines': 'PH',
    'Pologne': 'PL',
    'Portugal': 'PT',
    'Qatar': 'QA',
    'Roumanie': 'RO',
    'Russie': 'RU',
    'Rwanda': 'RW',
    'Saint-Kitts-et-Nevis': 'KN',
    'Sainte-Lucie': 'LC',
    'Saint-Vincent-et-les Grenadines': 'VC',
    'Samoa': 'WS',
    'Saint-Marin': 'SM',
    'São Tomé-et-Principe': 'ST',
    'Sénégal': 'SN',
    'Serbie': 'RS',
    'Seychelles': 'SC',
    'Sierra Leone': 'SL',
    'Singapour': 'SG',
    'Slovaquie': 'SK',
    'Slovénie': 'SI',
    'Îles Salomon': 'SB',
    'Somalie': 'SO',
    'Afrique du Sud': 'ZA',
    'Sri Lanka': 'LK',
    'Soudan': 'SD',
    'Soudan du Sud': 'SS',
    'Suriname': 'SR',
    'Suède': 'SE',
    'Suisse': 'CH',
    'Syrie': 'SY',
    'Tadjikistan': 'TJ',
    'Tanzanie': 'TZ',
    'Tchad': 'TD',
    'Thaïlande': 'TH',
    'Timor oriental': 'TL',
    'Togo': 'TG',
    'Tonga': 'TO',
    'Trinité-et-Tobago': 'TT',
    'Tunisie': 'TN',
    'Turkménistan': 'TM',
    'Turquie': 'TR',
    'Tuvalu': 'TV',
    'Uganda': 'UG',
    'Ukraine': 'UA',
    'Uruguay': 'UY',
    'Vanuatu': 'VU',
    'Vatican': 'VA',
    'Venezuela': 'VE',
    'Vietnam': 'VN',
    'Yémen': 'YE',
    'Zambie': 'ZM',
    'Zimbabwe': 'ZW',
  };